config/routes.rb
Rails.application.routes.draw do
  root to: "dashboard#index"

  devise_for :users,
    path: "",
    path_names: {
      sign_in:  "login",
      sign_out: "logout",
      sign_up:  "register"
    }

    resources :meals, only: [:new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user

  enum meal_type: { breakfast: 'breakfast', brunch: 'brunch', lunch: 'lunch', dinner: 'dinner' }

  validates :meal_type,     presence: true
  validates :fats,          presence: true
  validates :carbohydrates, presence: true
  validates :calories,      presence: true
  validates :proteins,      presence: true
  validates :user,          presence: true
  validate  :unique_meal_type_per_day

  private

  def unique_meal_type_per_day
    existing_meal = Meal.find_by(
      meal_type: meal_type,
      created_at: Time.now.beginning_of_day..Time.now.end_of_day
    )

    return if self == existing_meal

    if existing_meal
      errors.add(:meal_type, "#{meal_type} already logged for today.")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :meals, dependent: :destroy

  validates :email, presence: true

  devise(
    :database_authenticatable,
    :registerable,
    :recoverable,
    :rememberable,
  )
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @meals = current_user.meals.order(:meal_type).group_by { _1.created_at.to_date }
    respond_to :html
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  respond_to :html

  def new
    @meal = current_user.meals.new
    respond_with @meal
  end

  def create
    @meal = current_user.meals.new(meal_params)

    if @meal.save
      flash[:notice] = "New meal entry was added."
      redirect_to root_url
    else
      render :new
    end
  end

  def edit
    @meal = current_user.meals.find(params[:id])
  end

  def update
    @meal = current_user.meals.find(params[:id])

    if @meal.update(meal_params)
      flash[:notice] = "#{@meal.meal_type} has been edited successfully."
      redirect_to root_url
    else
      render :edit
    end
  end

  def destroy
    @meal = current_user.meals.find(params[:id])
    @meal.destroy

    flash[:notice] = "#{@meal.meal_type} has been deleted."
    redirect_to root_url
  end

  private

  def meal_params
    params.require(:meal).permit(:meal_type, :fats, :proteins, :calories, :carbohydrates)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<div class="container">
  <%= link_to "Add entry", new_meal_path %>
  <table class="table">
    <caption>Meals</caption>
    <thead>
      <tr>
        <th scope="col">Type</th>
        <th scope="col">Calories</th>
        <th scope="col">Proteins</th>
        <th scope="col">Carbohydrates</th>
        <th scope="col">Fats</th>
      </tr>
    </thead>
    <tbody>
      <% @meals.each do |date, meals| %>
        <tr>
          <th><%= date %><th>
        </tr>
        <% meals.each do |meal| %>
          <tr>
            <td><%= meal.meal_type %></td>
            <td><%= meal.calories %></td>
            <td><%= meal.proteins %></td>
            <td><%= meal.carbohydrates %></td>
            <td><%= meal.fats %></td>
            <td><%= link_to "Edit", edit_meal_path(meal), id: "#{meal.id}" %></td>
            <td><%= link_to "Destroy", meal_path(meal), id: "#{meal.id}", method: :delete, data: { confirm: "Are you sure?" } %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CaseStudy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <header class="container">
      <% if user_signed_in? %>
        <%= current_user.email %> | <%= link_to "Dashboard", root_path %> | <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      <% end %>
    </header>

    <br />

    <%= yield %>
  </body>
</html>

app/views/meals/_meal_form.html.erb
<% if meal.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(meal.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
      <% meal.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: meal do |form| %>
  <div>
    <%= form.label :meal_type %><br>
    <%= form.select :meal_type, Meal.meal_types.keys %>
  </div>

  <div>
    <%= form.label :proteins %><br>
    <%= form.text_field :proteins %>
  </div>

  <div>
    <%= form.label :calories %><br>
    <%= form.text_field :calories %>
  </div>

  <div>
    <%= form.label :carbohydrates %><br>
    <%= form.text_field :carbohydrates %>
  </div>

  <div>
    <%= form.label :fats %><br>
    <%= form.text_field :fats %>
  </div>

  <div>
    <%= form.submit "Save" %>
  </div>
<% end %>

app/views/meals/edit.html.erb
<div class="container">
  <h1>Add meal</h1>
  <%= render partial: "meal_form", locals: { meal: @meal } %>
</div>

app/views/meals/new.html.erb
<div class="container">
  <h1>Add meal</h1>
  <%= render partial: "meal_form", locals: { meal: @meal } %>
</div>